# MDI+: Example Usages

In [1]:
import sys
sys.path.append('..')

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import r2_score, mean_absolute_error, accuracy_score, roc_auc_score

from imodels.importance import RandomForestPlusRegressor, RandomForestPlusClassifier, \
    RidgeRegressorPPM, LassoRegressorPPM, IdentityTransformer, LogisticClassifierPPM
from imodels.importance.rf_plus import _fast_r2_score

In [2]:
def neg_mae(y_true, y_pred, **kwargs):
    """
    Evaluates negative mean absolute error
    """
    return -mean_absolute_error(y_true, y_pred, **kwargs)

In [3]:
# helper variables
rf_regressor = RandomForestRegressor(n_estimators=100, min_samples_leaf=5, max_features=0.33, random_state=331)
rf_classifier = RandomForestClassifier(n_estimators=100, min_samples_leaf=1, max_features="sqrt", random_state=331)

## 1. Regression Example

In [4]:
# generate data from linear model: y = x1 + x2 + N(0, 1)
n = 200
p = 10
s = 2
X = np.random.normal(size=(n, p))
beta = np.concatenate((np.ones(s), np.zeros(p-s)))
y = np.matmul(X, beta) + np.random.normal(size=n)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=12345)

### 1.1 MDI+ with default settings for regression

In [5]:
# fit RF+
rf_plus_model = RandomForestPlusRegressor(rf_model=rf_regressor)
rf_plus_model.fit(X_train, y_train)

In [6]:
# make predictions with RF+
preds = rf_plus_model.predict(X_test)
r2_score(y_test, preds)

0.7248366373142732

In [7]:
# get MDI+ scores (higher r^2 value = greater importance)
mdi_plus_scores = rf_plus_model.get_mdi_plus_scores(X_train, y_train)
mdi_plus_scores.sort_values("importance", ascending=False)

   var  importance
0    0    0.378451
1    1    0.278550
7    7    0.003884
3    3   -0.001895
8    8   -0.003159
4    4   -0.003348
6    6   -0.004778
2    2   -0.008542
5    5   -0.008810
9    9   -0.009128

In [8]:
# fit RF+
rf_plus_model = RandomForestPlusRegressor(rf_model=rf_regressor, sample_split="oob", prediction_model=RidgeRegressorPPM(loo=False))
rf_plus_model.fit(X_train, y_train)

# get MDI+ scores (higher r^2 value = greater importance)
mdi_plus_scores = rf_plus_model.get_mdi_plus_scores(X_train, y_train, pval=True)
mdi_plus_scores.sort_values("importance", ascending=False)

   var  importance
0    0    0.339726
1    1    0.226145
7    7   -0.024963
3    3   -0.036795
4    4   -0.037678
6    6   -0.041834
8    8   -0.043024
5    5   -0.043502
9    9   -0.046058
2    2   -0.046729

In [9]:
# build F dataframe
df_F = pd.DataFrame({
    i: pd.DataFrame.from_dict(d, orient='index')['F']
    for i, d in enumerate(rf_plus_model.mdi_plus_.pvalues_)
})
df_F

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,14.535145,34.472483,61.281095,32.808080,44.340207,32.537975,55.249613,39.795842,33.739729,37.238354,...,42.517911,36.849930,28.081624,29.103224,45.252297,50.957520,47.448379,31.490972,37.870566,49.798758
1,23.140194,44.106140,36.607039,21.085124,21.550500,16.572907,16.514812,43.976732,16.896261,7.379704,...,33.129720,25.055161,16.391972,38.054089,28.230065,55.812036,42.715011,37.457168,37.525621,21.784536
2,-8.769849,0.215292,-4.876205,-1.986423,-1.388111,0.000000,0.000000,-4.988201,-0.065681,0.000000,...,0.000000,-2.209707,0.000000,0.973170,-1.876820,1.349417,0.000000,-3.787173,-1.978465,-5.537546
3,-0.018446,0.708474,0.000000,0.000000,-5.191939,-0.177441,2.955627,-1.131006,-1.691545,0.000000,...,0.000000,-1.174958,0.000000,-1.987298,-1.889042,0.000000,1.522463,0.000000,0.000000,-7.365776
4,3.290302,0.000000,-0.940264,-1.505160,0.642023,-2.716436,-6.102467,0.097195,-14.695204,-1.544611,...,-0.698786,0.000000,0.000000,0.112943,-4.350245,0.000000,0.000000,3.624342,-4.478701,4.887628
5,-1.781124,-6.552516,-7.896050,-0.076881,0.000000,0.312077,-0.740182,0.000000,0.000000,-1.111299,...,-1.283733,-3.050359,-12.924936,-8.351922,-1.657743,-1.921336,0.000000,-3.098276,0.000000,-0.967472
6,0.000000,1.273762,7.845618,-2.871410,0.000000,0.000000,-1.426908,0.000000,0.000000,-5.964754,...,-2.319546,0.000000,-0.263045,-2.417525,-4.311979,0.000000,-3.017091,-5.762947,3.631771,5.159617
7,0.000000,0.000000,-2.221920,-0.448867,0.385754,-1.002837,0.000000,-1.474103,0.000000,0.000000,...,0.000000,0.000000,0.427282,-0.347045,-7.121407,-5.030871,9.350576,1.178870,0.000000,0.000000
8,-4.229093,-5.332477,0.000000,0.268358,-3.788583,-4.711916,-1.668027,0.000000,0.000000,0.000000,...,-5.358614,-17.998785,0.000000,0.000000,-0.138088,-0.280340,-1.362689,0.000000,0.000000,1.541603
9,-0.101509,0.000000,-4.066754,0.000000,-0.124388,-6.714793,-1.234753,-6.000839,6.596881,0.000000,...,0.610023,3.208981,0.000000,4.686508,-0.014730,2.260402,0.000000,-3.860699,-3.919428,0.000000

In [10]:
# build p dataframe
df_p = pd.DataFrame({
    i: pd.DataFrame.from_dict(d, orient='index')['p']
    for i, d in enumerate(rf_plus_model.mdi_plus_.pvalues_)
})
df_p

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,6.628993e-09,4.962603e-11,7.046676e-21,1.546183e-16,1.564382e-19,6.245397e-16,1.328391e-15,3.710263e-17,4.941459e-17,1.157983e-18,...,1.371137e-16,9.039742e-18,1.714567e-15,5.908147e-14,1.131072e-16,2.763313e-18,7.048511e-22,1.097506e-13,7.514187e-18,1.591721e-19
1,2.518079e-14,4.948354e-14,4.694921e-18,3.814670e-10,1.438878e-09,8.909955e-08,3.523688e-10,4.213813e-14,5.069187e-11,1.700454e-05,...,4.859445e-14,3.527158e-13,9.451286e-11,8.017564e-15,3.049776e-09,5.767914e-16,2.829270e-17,6.730222e-16,2.718990e-12,1.383135e-10
2,1.000000e+00,8.219100e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,3.837180e-01,1.000000e+00,2.581669e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
3,1.000000e+00,5.160298e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,5.951678e-02,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.243710e-01,1.000000e+00,1.000000e+00,1.000000e+00
4,4.983564e-02,1.000000e+00,1.000000e+00,1.000000e+00,4.676356e-01,1.000000e+00,1.000000e+00,9.804039e-01,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,7.683397e-01,1.000000e+00,1.000000e+00,1.000000e+00,3.673829e-02,1.000000e+00,2.311386e-02
5,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,6.537980e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
6,1.000000e+00,2.864111e-01,1.981428e-04,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.493749e-02,1.354780e-02
7,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,5.961178e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,6.875814e-01,1.000000e+00,1.000000e+00,1.000000e+00,4.781782e-07,3.049429e-01,1.000000e+00,1.000000e+00
8,1.000000e+00,1.000000e+00,1.000000e+00,8.133299e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.200684e-01
9,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,3.888072e-03,1.000000e+00,...,5.160528e-01,5.814566e-02,1.000000e+00,2.276868e-02,1.000000e+00,8.047369e-02,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [11]:
pd.concat([mdi_plus_scores, df_p.median(axis=1).round(3)], axis=1).rename(
    columns={"var": "Variable", "importance": "MDI+ importance", 0: "Median p-value"}
)

   Variable  MDI+ importance  Median p-value
0         0         0.339726             0.0
1         1         0.226145             0.0
2         2        -0.046729             1.0
3         3        -0.036795             1.0
4         4        -0.037678             1.0
5         5        -0.043502             1.0
6         6        -0.041834             1.0
7         7        -0.024963             1.0
8         8        -0.043024             1.0
9         9        -0.046058             1.0

### 1.2 MDI+ with custom partial prediction model and evaluation metric(s)

In [12]:
# fit RF+ with custom partial prediction model
rf_plus_model = RandomForestPlusRegressor(rf_model=rf_regressor, prediction_model=LassoRegressorPPM())
rf_plus_model.fit(X_train, y_train)

In [13]:
# get MDI+ scores with custom evaluation metrics/scorers
mdi_plus_scores = rf_plus_model.get_mdi_plus_scores(X_train, y_train, scoring_fns={"rsq_score": _fast_r2_score, "negative_mae": neg_mae})
mdi_plus_scores.sort_values("rsq_score", ascending=False)

   var  rsq_score  negative_mae
0    0   0.381474     -1.096737
1    1   0.286451     -1.185933
7    7   0.001401     -1.445046
3    3  -0.002533     -1.446980
6    6  -0.002841     -1.448113
8    8  -0.002865     -1.447372
4    4  -0.003257     -1.450394
2    2  -0.003511     -1.447666
5    5  -0.004102     -1.448063
9    9  -0.006070     -1.446311

### 1.3 MDI+ with custom transformer

The example below is equivalent to running RF+ with `include_raw=True`

In [14]:
# fit RF+ with custom transformer
rf_plus_model = RandomForestPlusRegressor(rf_model=rf_regressor, include_raw=False, add_transformers=[IdentityTransformer()])
rf_plus_model.fit(X_train, y_train)

In [15]:
# get MDI+ scores
mdi_plus_scores = rf_plus_model.get_mdi_plus_scores(X_train, y_train)
mdi_plus_scores.sort_values("importance", ascending=False)

   var  importance
0    0    0.381143
1    1    0.281181
7    7    0.002603
3    3   -0.002328
8    8   -0.003382
4    4   -0.004174
6    6   -0.004737
5    5   -0.009093
2    2   -0.009569
9    9   -0.010188

### 1.4 Choosing the GLM and scoring metric via stability score

There are many choices of GLMs and scoring metrics that can be made within the MDI+ framework.

One way to select the GLM and scoring metric in MDI+ is by evaluating the stability of the feature importances/rankings for each choice of GLM/metric and taking the GLM/metric that is the most stable across different bootstrap samples of trees. For example, we can take the GLM and metric with the highest stability score, as measured by RBO below.

In [ ]:
n_bootstraps = 25
prediction_models = {"ridge": RidgeRegressorPPM(), "lasso": LassoRegressorPPM()}
scoring_fns = {"r2": _fast_r2_score, "neg_mae": neg_mae}
stability_dict = {}
for model_name, prediction_model in prediction_models.items():
    # fit RF+
    rf_plus_model = RandomForestPlusRegressor(rf_model=rf_regressor, prediction_model=prediction_model)
    rf_plus_model.fit(X_train, y_train)
    # get MDI+ scores
    mdi_plus_scores = rf_plus_model.get_mdi_plus_scores(X_train, y_train, scoring_fns=scoring_fns)
    # get MDI+ stability scores
    mdi_plus_stability_scores = rf_plus_model.get_mdi_plus_stability_scores(B=n_bootstraps)
    stability_dict[model_name] = mdi_plus_stability_scores

In [ ]:
pd.concat(stability_dict, axis=0).reset_index().rename(columns={"level_0": "ppm"}).drop(columns=["level_1"]).sort_values("RBO", ascending=False)

### 1.5 Aggregating multiple MDI+ rankings in an ensemble

Instead of choosing a single GLM and metric to use in MDI+, it may be preferable in some cases to aggregate MDI+ feature importances/rankings across multiple choices of GLMs and metrics.

One naive method for doing this ensembling is to take the median rank across each choice of GLM and metric (as shown below). However, more creative ensembling schemes can also be explored.

In [ ]:
prediction_models = {"ridge": RidgeRegressorPPM(), "lasso": LassoRegressorPPM()}
scoring_fns = {"r2": _fast_r2_score, "neg_mae": neg_mae}
mdi_plus_scores_dict = {}
for model_name, prediction_model in prediction_models.items():
    # fit RF+
    rf_plus_model = RandomForestPlusRegressor(rf_model=rf_regressor, prediction_model=prediction_model)
    rf_plus_model.fit(X_train, y_train)
    # get MDI+ scores
    mdi_plus_scores = rf_plus_model.get_mdi_plus_scores(X_train, y_train, scoring_fns=scoring_fns)
    for col in mdi_plus_scores.columns:
        if col != "var":
            mdi_plus_scores = mdi_plus_scores.rename(columns={col: model_name + "_" + col})
    mdi_plus_scores_dict[model_name] = mdi_plus_scores

In [ ]:
mdi_plus_scores_df = pd.concat([df.set_index('var') for df in mdi_plus_scores_dict.values()], axis=1)
mdi_plus_ranks_df = mdi_plus_scores_df.rank(ascending=False).median(axis=1)
mdi_plus_ranks_df = pd.DataFrame(mdi_plus_ranks_df, columns=["median_rank"]).reset_index()
mdi_plus_ranks_df.sort_values("median_rank")

## 2. Classification Example

In [4]:
# generate data from logistic model: logit(E[Y|X]) = x1 + x2
n = 200
p = 10
s = 2
X = np.random.normal(size=(n, p))
beta = np.concatenate((np.ones(s), np.zeros(p-s)))
probs = 1 / (1 + np.exp(-np.matmul(X, beta)))
y = (np.random.uniform(size=n) < probs) * 1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=12345)

### 2.1 MDI+ with default classification settings

In [5]:
# fit RF+
rf_plus_model = RandomForestPlusClassifier(rf_model=rf_classifier)
rf_plus_model.fit(X_train, y_train)

In [6]:
# make predictions with RF+
preds = rf_plus_model.predict(X_test)
prob_preds = rf_plus_model.predict_proba(X_test)
accuracy_score(y_test, preds), roc_auc_score(y_test, prob_preds[:, 1])

(0.7727272727272727, 0.8511029411764706)

In [7]:
# get MDI+ scores (higher ngative log-loss value = greater importance)
mdi_plus_scores = rf_plus_model.get_mdi_plus_scores(X_train, y_train)
mdi_plus_scores.sort_values("importance", ascending=False)

   var  importance
0    0   -0.632659
1    1   -0.652891
7    7   -0.688870
4    4   -0.689596
8    8   -0.689879
6    6   -0.691319
9    9   -0.691913
3    3   -0.694005
5    5   -0.694353
2    2   -0.694670

In [8]:
# fit RF+
rf_plus_model = RandomForestPlusClassifier(rf_model=rf_classifier, sample_split="oob", prediction_model=LogisticClassifierPPM(loo=False))
rf_plus_model.fit(X_train, y_train)

# get MDI+ scores (higher r^2 value = greater importance)
mdi_plus_scores = rf_plus_model.get_mdi_plus_scores(X_train, y_train, pval=True)
mdi_plus_scores.sort_values("importance", ascending=False)

   var  importance
3    3   -0.821570
4    4   -0.824042
5    5   -0.837694
1    1   -0.846746
2    2   -0.847129
0    0   -0.851427
7    7   -0.855281
6    6   -0.860647
9    9   -0.860970
8    8   -0.887796

In [11]:
# build chi2 dataframe
df_chi2 = pd.DataFrame({
    i: pd.DataFrame.from_dict(d, orient='index')['chi2']
    for i, d in enumerate(rf_plus_model.mdi_plus_.pvalues_)
})
df_chi2

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,2.227306,-10.405129,1.282934,3.442634,-3.653446e+01,17.175441,-0.105274,-12.265378,-47.502948,-59.373504,...,-19.699743,39.947295,0.000000,2.056162,-12.182511,-2.697980,-2.690506e+01,14.724927,16.847278,-4.055507
1,-32.462499,-4.603949,-10.926767,2.499376,-8.657092e+00,-10.984320,-23.644764,-4.501491,-1.873156,0.316926,...,25.551836,1.379938,3.953615,-40.663772,0.000000,-3.793230,-2.434503e+01,-28.149939,-3.201427,-13.769131
2,-1.494521,-4.803731,5.730230,-5.107503,2.842171e-14,-13.191534,0.000000,0.000000,-14.134991,3.327813,...,6.066607,0.309941,4.923522,-35.341117,-1.276867,-6.682988,2.842171e-14,0.000000,-22.300503,0.000000
3,-8.318236,-0.566716,2.694198,-31.573879,-5.381713e+00,-1.195095,0.000000,-21.029800,0.000000,-6.126506,...,-12.425267,-9.192781,-2.323628,-1.609805,-13.171953,-7.890494,-2.447182e+01,-24.673701,-20.338422,-5.628905
4,-6.891187,-25.437081,2.109046,-16.106959,-2.659740e-02,5.977366,-15.457768,-20.705505,0.736647,-27.607747,...,-19.528194,-18.274984,-2.609981,0.000000,-6.066981,-6.889745,3.776231e-01,2.231423,-3.467309,-5.174258
5,-3.657645,-0.508857,0.000000,-10.524233,-2.501507e+00,0.000000,-13.361318,-24.848656,-14.315923,-23.777226,...,1.728024,-5.131137,4.873300,-16.437113,-18.921214,-11.818648,-1.907663e+01,-7.355803,-34.016669,-5.206669
6,-1.498691,-1.397913,-6.962032,-10.834680,3.212410e+00,0.000000,-13.809234,-20.189582,-2.569593,0.000000,...,-1.345715,11.718672,-26.943614,-25.361870,-9.864806,-3.883771,-5.705890e+01,-3.652249,-0.108322,3.784554
7,-19.174644,-9.712586,-2.527286,0.000000,-2.440721e+01,-42.739375,-0.985876,4.287228,0.000000,0.000000,...,1.266593,-13.669373,0.850060,0.000000,-3.479234,-45.478941,-2.962436e+01,-1.866373,-3.270051,-4.265951
8,0.000000,3.056185,-12.519730,12.453027,-4.900487e+01,-15.278522,-7.253577,0.000000,-16.326146,-40.049679,...,-18.369424,-4.627371,2.747113,-3.356958,-19.564620,-16.713164,-2.855736e+01,0.000000,-48.794852,-1.039731
9,1.008741,-2.825982,-22.589054,-8.762855,-1.459459e+00,-0.176799,-6.106150,-39.488126,-3.078847,-24.755768,...,-3.642851,-6.175008,2.124847,-17.005361,0.393474,-14.529329,-8.370456e+00,0.000000,-28.499422,-20.524107

In [12]:
# build p dataframe
df_p = pd.DataFrame({
    i: pd.DataFrame.from_dict(d, orient='index')['p']
    for i, d in enumerate(rf_plus_model.mdi_plus_.pvalues_)
})
df_p

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.299992,1.000000,0.277176,0.205786,1.00000,0.000849,1.0,1.000000,1.000000,1.000000,...,1.000000,3.079054e-08,1.000000,0.4044,1.000000,1.0,1.000000,0.000520,0.000112,1.000000
1,1.000000,1.000000,1.000000,0.052050,1.00000,1.000000,1.0,1.000000,1.000000,0.668533,...,0.000007,6.072306e-01,0.082461,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000
2,1.000000,1.000000,0.038290,1.000000,1.00000,1.000000,1.0,1.000000,1.000000,0.102683,...,0.010701,9.839803e-01,0.022853,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000
3,1.000000,1.000000,0.147829,1.000000,1.00000,1.000000,1.0,1.000000,1.000000,1.000000,...,1.000000,1.000000e+00,1.000000,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000
4,1.000000,1.000000,0.524177,1.000000,1.00000,0.023559,1.0,1.000000,0.836294,1.000000,...,1.000000,1.000000e+00,1.000000,1.0000,1.000000,1.0,0.977026,0.372268,1.000000,1.000000
5,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.0,1.000000,1.000000,1.000000,...,0.277107,1.000000e+00,0.093353,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000
6,1.000000,1.000000,1.000000,1.000000,0.12417,1.000000,1.0,1.000000,1.000000,1.000000,...,1.000000,2.984461e-03,1.000000,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,0.064013
7,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.0,0.156161,1.000000,1.000000,...,0.279273,1.000000e+00,0.450540,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000
8,1.000000,0.234392,1.000000,0.005978,1.00000,1.000000,1.0,1.000000,1.000000,1.000000,...,1.000000,1.000000e+00,0.543616,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000
9,0.581217,1.000000,1.000000,1.000000,1.00000,1.000000,1.0,1.000000,1.000000,1.000000,...,1.000000,1.000000e+00,0.209074,1.0000,0.897209,1.0,1.000000,1.000000,1.000000,1.000000

In [15]:
pd.concat([mdi_plus_scores, df_p.median(axis=1).round(3)], axis=1).rename(
    columns={"var": "Variable", "importance": "MDI+ importance", 0: "Median p-value"}
)

   Variable  MDI+ importance  Median p-value
0         0        -0.851427             1.0
1         1        -0.846746             1.0
2         2        -0.847129             1.0
3         3        -0.821570             1.0
4         4        -0.824042             1.0
5         5        -0.837694             1.0
6         6        -0.860647             1.0
7         7        -0.855281             1.0
8         8        -0.887796             1.0
9         9        -0.860970             1.0

In [ ]:
pd.concat([mdi_plus_scores, df_p.mean(axis=1).round(3)], axis=1).rename(
    columns={"var": "Variable", "importance": "MDI+ importance", 0: "Mean p-value"}
)

   Variable  MDI+ importance  Median p-value
0         0        -0.851427           0.662
1         1        -0.846746           0.727
2         2        -0.847129           0.891
3         3        -0.821570           0.858
4         4        -0.824042           0.838
5         5        -0.837694           0.892
6         6        -0.860647           0.894
7         7        -0.855281           0.906
8         8        -0.887796           0.895
9         9        -0.860970           0.882